name: Code Quality Metrics
on: [push, pull_request]
jobs:
  calculate-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make PMD executable
        run: chmod +x ./pmd-bin/bin/pmd
      - name: Make script executable
        run: chmod +x ./calculate_metrics.sh
      - name: Calculate Metrics
        run: ./calculate_metrics.sh